[dependencies]
clap = '2.33.0'
crossterm = '0.9.1'
colored = "*"

[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
license = 'MIT'
name = 'encore'
version = '0.1.0'

[[example]]
name = 'minimal'

[[example]]
name = 'clap'
